name: Daily Sync
on:
  schedule:
    - cron: '30 7 * * *'

jobs:
  remote-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4.0'
      - run: bundle install
      - run: ./script/remote-sync
        env:
          GIT_AUTHOR_NAME: 'Brandon Keepers'
          GIT_AUTHOR_EMAIL: 'bkeepers@github.com'
      - run: ./script/site-test
